### PR TITLE
Resource file for romanian language

### PR DESCRIPTION
**Pull request by TigerxWood**

### CODE REVIEW

**Comment by bricelam** [comment]
There are two resources not in this file:

Key | Value
--- | ---
IDS_RESIZE_PICTURES | Resize pictures
IDS_RESIZE_PICTURES_HERE | Resize pictures here

**Comment by bricelam** [comment]
Thanks for your contribution! You can test it out by downloading here: https://ci.appveyor.com/project/bricelam/imageresizer/branch/develop/artifacts

**Comment by TigerxWood** [comment]
I have a question. What is the meaning of Fallback encoder. It is the actual encoder who do the resize work or what ?
And I noticed that the program loads the language similar with that in the Windows system, but there are users who have installed and have licence only for the english version, so they will never see translated version if they want. So it will be usefull to implement a language selector in Advanced settings or some icon on the main interface.

**Comment by bricelam** [comment]
The fallback encoder is used when you resize a kind of image that the computer can read, but not write. It's almost never used.

Filed #55 to allow selecting a language.

**Pull request merged**
